---
kind: pipeline
name: TensorFlow 1.13.1

platform:
  os: linux
  arch: amd64

steps:
- name: custom_op
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd custom_op/user_ops
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make

- name: inference_cc
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/cc/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow_src

- name: inference_c
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/c/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow_src

- name: inference_go
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=/tensorflow_dist:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LD_LIBRARY_PATH}"
  - "export LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LIBRARY_PATH}"
  - WDIR=$PWD
  - mkdir -p $GOPATH/src/github.com/tensorflow
  - cd $GOPATH/src/github.com/tensorflow
  - git clone -b v1.13.1 --single-branch --depth 1 https://github.com/tensorflow/tensorflow.git
  - cd $WDIR
  - cd inference/go/
  - ./build.sh
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow_src

- name: example_keras
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/keras/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow_src

- name: example_simple
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/simple/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow_src

- name: example_resize
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/resize/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow_src

- name: event_writer
  pull: never
  image: tensorflow-cmake:1.13.1-devel
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/event_writer/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow_src

---
kind: pipeline
name: TensorFlow 1.12.0

platform:
  os: linux
  arch: amd64

steps:
- name: custom_op
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd custom_op/user_ops
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make

- name: inference_cc
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/cc/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_c
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/c/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_go
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0-go1.11
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=/tensorflow_dist:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LD_LIBRARY_PATH}"
  - "export LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LIBRARY_PATH}"
  - WDIR=$PWD
  - mkdir -p $GOPATH/src/github.com/tensorflow
  - cd $GOPATH/src/github.com/tensorflow
  - git clone -b v1.12.0 --single-branch --depth 1 https://github.com/tensorflow/tensorflow.git
  - cd $WDIR
  - cd inference/go/
  - ./build.sh
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_keras
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/keras/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_simple
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/simple/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_resize
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0-opencv3.4.2
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/resize/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: event_writer
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.12.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/event_writer/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

---
kind: pipeline
name: TensorFlow 1.11.0

platform:
  os: linux
  arch: amd64

steps:
- name: custom_op
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd custom_op/user_ops
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make

- name: inference_cc
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/cc/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_c
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/c/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_go
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0-go1.11
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=/tensorflow_dist:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LD_LIBRARY_PATH}"
  - "export LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LIBRARY_PATH}"
  - WDIR=$PWD
  - mkdir -p $GOPATH/src/github.com/tensorflow
  - cd $GOPATH/src/github.com/tensorflow
  - git clone -b v1.11.0 --single-branch --depth 1 https://github.com/tensorflow/tensorflow.git
  - cd $WDIR
  - cd inference/go/
  - ./build.sh
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_keras
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/keras/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_simple
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/simple/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_resize
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0-opencv3.4.2
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/resize/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: event_writer
  pull: never
  image: tensorflow:ubuntu16.04-cuda10.0-bazel0.16.1-tensorflow1.11.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/event_writer/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

---
kind: pipeline
name: TensorFlow 1.10.0

platform:
  os: linux
  arch: amd64

steps:
- name: custom_op
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd custom_op/user_ops
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make

- name: inference_cc
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/cc/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_c
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/c/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_go
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0-go1.10
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=/tensorflow_dist:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LD_LIBRARY_PATH}"
  - "export LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LIBRARY_PATH}"
  - WDIR=$PWD
  - mkdir -p $GOPATH/src/github.com/tensorflow
  - cd $GOPATH/src/github.com/tensorflow
  - git clone -b v1.10.0 --single-branch --depth 1 https://github.com/tensorflow/tensorflow.git
  - cd $WDIR
  - cd inference/go/
  - ./build.sh
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_keras
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/keras/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_simple
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/simple/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_resize
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0-opencv3.4.2
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/resize/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: event_writer
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.2-bazel0.16.1-tensorflow1.10.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/event_writer/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

---
kind: pipeline
name: TensorFlow 1.9.0

platform:
  os: linux
  arch: amd64

steps:
- name: custom_op
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd custom_op/user_ops
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make

- name: inference_cc
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/cc/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_c
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd inference/c/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: inference_go
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0-go1.10
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=/tensorflow_dist:$${LD_LIBRARY_PATH}"
  - "export LD_LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LD_LIBRARY_PATH}"
  - "export LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LIBRARY_PATH}"
  - WDIR=$PWD
  - mkdir -p $GOPATH/src/github.com/tensorflow
  - cd $GOPATH/src/github.com/tensorflow
  - git clone -b v1.9.0 --single-branch --depth 1 https://github.com/tensorflow/tensorflow.git
  - cd $WDIR
  - cd inference/go/
  - ./build.sh
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_keras
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/keras/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_simple
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/simple/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: example_resize
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0-opencv3.4.2
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/resize/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

- name: event_writer
  pull: never
  image: tensorflow:ubuntu16.04-cuda9.0-bazel0.11.0-tensorflow1.9.0
  commands:
  - "export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}"
  - cd examples/event_writer/
  - cmake . -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
  - make
  environment:
    TENSORFLOW_BUILD_DIR: /tensorflow_dist
    TENSORFLOW_SOURCE_DIR: /tensorflow

---
kind: signature
hmac: b15900693226398445e907aa7854bfee88fbcb3a6feb8862bcd76fd2e40185e0

...
