pipeline:
  custom_op:
    image: tensorflow:cuda9-ubuntu16.04-tf1.9
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - cd custom_op/user_ops
      - cmake .
      - make
  inference_cc:
    image: tensorflow:cuda9-ubuntu16.04-tf1.9
    environment:
      - TENSORFLOW_SOURCE_DIR=/tensorflow
      - TENSORFLOW_BUILD_DIR=/tensorflow_dist
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - cd inference/cc/
      - cmake .
      - make
  inference_c:
    image: tensorflow:cuda9-ubuntu16.04-tf1.9
    environment:
      - TENSORFLOW_SOURCE_DIR=/tensorflow
      - TENSORFLOW_BUILD_DIR=/tensorflow_dist
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - cd inference/c/
      - cmake .
      - make
  inference_go:
    image: tensorflow:cuda9-go-ubuntu16.04-tf1.9
    environment:
      - TENSORFLOW_SOURCE_DIR=/tensorflow
      - TENSORFLOW_BUILD_DIR=/tensorflow_dist
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - export LD_LIBRARY_PATH=/tensorflow_dist:$${LD_LIBRARY_PATH}
      - export LD_LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LD_LIBRARY_PATH}
      - export LIBRARY_PATH=$${TENSORFLOW_BUILD_DIR}/:$${LIBRARY_PATH}
      - go get github.com/tensorflow/tensorflow/tensorflow/go
      - cd inference/go/
      - ./build.sh
  example_keras:
    image: tensorflow:cuda9-ubuntu16.04-tf1.9
    environment:
      - TENSORFLOW_SOURCE_DIR=/tensorflow
      - TENSORFLOW_BUILD_DIR=/tensorflow_dist
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - cd examples/keras/
      - cmake .
      - make
  example_simple:
    image: tensorflow:cuda9-ubuntu16.04-tf1.9
    environment:
      - TENSORFLOW_SOURCE_DIR=/tensorflow
      - TENSORFLOW_BUILD_DIR=/tensorflow_dist
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - cd examples/simple/
      - cmake .
      - make
  example_resize:
    image: tensorflow:cuda9-opencv3.1-ubuntu16.04-tf1.9
    environment:
      - TENSORFLOW_SOURCE_DIR=/tensorflow
      - TENSORFLOW_BUILD_DIR=/tensorflow_dist
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - cd examples/resize/
      - cmake .
      - make
  event_writer:
    image: tensorflow:cuda9-ubuntu16.04-tf1.9
    environment:
      - TENSORFLOW_SOURCE_DIR=/tensorflow
      - TENSORFLOW_BUILD_DIR=/tensorflow_dist
    commands:
      - export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$${LD_LIBRARY_PATH}
      - cd examples/event_writer/
      - cmake .
      - make
