
t13:
	sudo docker build \
	  --build-arg CHECKOUT_TF_SRC=1 \
	  -t tensorflow-cmake:1.13.1-devel \
	  -f tensorflow-cmake-1.13.1-devel.Dockerfile .

t14:
	sudo docker build \
	  --build-arg CHECKOUT_TF_SRC=1 \
	  -t tensorflow-cmake:1.14.0-devel \
	  -f tensorflow-cmake-1.14.0-devel.Dockerfile .